### ISSUE TITLE
Is it possible to create an alternative to bodycomposition?

### ISSUE THREAD

**Issue by RobertWojtowicz** [lswiderski/yet-another-garmin-connect-client#1]
Hi, @lswiderski

You handled the authorization to Garmin, would you be able to make an executable program version like bodycomposition?

BR,
Robert

**Comment by lswiderski** [comment]
Hi @RobertWojtowicz 

Yes, I can do it. But currently I'm totally lack of time. When I find a moment I will make a console application exposing this one endpoint. There will probably be breaking changes in the future because this is just the beginning of work on the client and I haven't fully thought through its api yet

However, until that happens maybe a docker image will suffice?
https://hub.docker.com/r/lswiderski/yet-another-garmin-connect-client-api

Endpoint: /upload on port 8080
paylod:
```
{
  "timeStamp": -1, // -1 for Time Now, or UNIX timestamp
  "weight": 67, // kg
  "percentFat": 14.9, // %
  "percentHydration": 58.4, // %
  "boneMass": 3.3, // kg
  "muscleMass": 55.1, // kg
  "visceralFatRating": 7,
  "physiqueRating": 5,
  "metabolicAge": 25,
  "bodyMassIndex": 20.8,
  "email": "{{email}}",
  "password": "{{password}}"
}

**Comment by RobertWojtowicz** [comment]
Hi, @lswiderski 

Thanks for the info, I'm interested in a standalone solution without using an additional gateway/api external just send to garmin directly like bodycomposition does.

P.S. When I have a moment :) I'll take a look at this docker image.

BR,
Robert

**Comment by lswiderski** [comment]
@RobertWojtowicz 

Please check it https://github.com/lswiderski/yet-another-garmin-connect-client/releases/tag/cli-v0.0.1

Please keep in mind that this is a test build, made quickly in spare time. I tested it only in windows environment. usage is almost  the same as in bodycomposition. See --help or ask here if you have questions.

cheers

**Comment by RobertWojtowicz** [comment]
Hi @lswiderski

Thank you very much, it works :)

It works under Linux (quite a thick package), can you add a function not to write to fit files (--no-fit-file ?), for now I added myself to script to delete tmp directory.

Can I request archive files in tar.gz format instead of zip? it is easier to manage with bash.
Where is the --visceral-fat-mass parameter? I haven't seen that in Garmin.

P.S. I made an update of my project based on YAGCC.

BR,
Robert

**Comment by lswiderski** [comment]
@RobertWojtowicz Sorry for the late reply.
I have a newborn at home, so my activity will be limited for a while. As soon as everything is fairly back to "normal" I will take care of it.

**Comment by lswiderski** [comment]
@RobertWojtowicz  small update as requested. Now YAGCC do not create .fit file on disk, only in memory.

 about --visceral-fat-mass I cannot see it too, But it is available in FIT API so it exist here too  

https://github.com/lswiderski/yet-another-garmin-connect-client/releases/tag/cli-v0.0.2
