### ISSUE TITLE
Segmentation fault in arm package

### ISSUE THREAD

**Issue by RobertWojtowicz** [lswiderski/yet-another-garmin-connect-client#5]
Hi @lswiderski 

Raspberry users report a problem, I recreated and on my RPi (Debian 11 & 12)
https://github.com/RobertWojtowicz/miscale2garmin/issues/34

BR,
Robert

**Comment by lswiderski** [comment]
@RobertWojtowicz 

Hi I did some research and found that, unfortunately due to dotnet limitations It do not support ARMv6 that it's inside RPI 0 . It can works on RPI 2,3,4, 2W

https://github.com/dotnet/runtime/issues/3013
https://www.raspberrypi.com/documentation/computers/processors.html

**Comment by RobertWojtowicz** [comment]
The solution is to switch to Python 3 API wrapper: https://github.com/cyberjunky/python-garminconnect
Also works great on old RPIs.
