### ISSUE TITLE
Support for blood pressure fit type

### ISSUE THREAD

**Issue by tinuva** [lswiderski/yet-another-garmin-connect-client#7]
Currently it looks like this only support `CreateWeightBodyCompositionFitFile` in https://github.com/lswiderski/yet-another-garmin-connect-client/blob/5500b06abeabc7bb9b01a23316991746992bc9bc/src/FitFileCreator.cs#L17

Could you also add a `CreateBloodPressureCompositionFitFile` function that is usable with the CLI as a start?

The format I found is described in https://developers.google.com/fit/scenarios/write-bp-data

**Comment by lswiderski** [comment]
Hi @tinuva 

As requested uploadbloodpressure command is now available in CLI and API

https://github.com/lswiderski/yet-another-garmin-connect-client/releases/tag/cli-v0.0.3
